[project]
name = "midnight-journal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "textual>=6.5.0",
    "textual-dev>=1.8.0",
    "rich>=13.0.0",
]
