[project]
name = "midnight-journal"
version = "0.6"
description = "A simple TUI Journal"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "textual>=6.5.0",
    "rich>=13.0.0",
]
[project.scripts]
midnight_journal = "midnight_journal.entry_points:midnight_journal"